name: how-to-expected-goals
channels:
 - conda-forge
 - defaults
dependencies:
 - matplotlib=3.0.2
 - pandas=0.23.4
 - pyarrow=0.12.0
 - python=3.7.1
 - scikit-learn=0.20.2
 - scikit-plot=0.3.7
 - xgboost=0.81
